wmaker: remove apercu struct check artefact
This patch is removing the check for the legacy_minipreview_config struct
which was removed in commit fa8121ee6106bb0843fc90f441dd33a2c8cc09d0
Without it we can see the error below when running make check:

Error: structure "legacy_minipreview_config" was not found in ./defaults.c